name: generate-argocd-application

inputs:
  github-token:
    description: GitHub API Token to interact with GitHub repo
    required: true
  overlay:
    description: Overlay name to use build with kustomize
    required: true
  namespace:
    description: Kubernetes namespace to deploy to
    required: true
  git-user-email:
    description: Git user email
    required: true
  git-user-name:
    description: Git user name
    required: true

runs:
  using: 'composite'
  steps:
    - run: |
        GITHUB_TOKEN="${{ inputs.github-token }}" \
          OVERLAY="${{ inputs.overlay }}" \
          NAMESPACE="${{ inputs.namespace }}" \
          GIT_USER_EMAIL="${{ inputs.git-user-email }}" \
          GIT_USER_NAME="${{ inputs.git-user-name }}" \
          ${{ github.action_path }}/action.sh
      shell: bash
