apiVersion: v1
data:
  GITHUB_SHA: 5fbbed2a4c9709fa788f3acd47dc4a91adb41faf
  NAMESPACE: pr-73
  OVERLAY: staging
  SERVICE_NAME: ingress
kind: ConfigMap
metadata:
  name: ingress-metadata-58tt5gk4k6
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: frontend
          servicePort: 80
        path: /
      - backend:
          serviceName: service-foo
          servicePort: 80
        path: /foo
      - backend:
          serviceName: service-bar
          servicePort: 80
        path: /bar
