apiVersion: v1
data:
  GITHUB_SHA: c5d548f5aec5f362ef1079e98336bca2555739f4
  NAMESPACE: develop
  OVERLAY: develop
  SERVICE_NAME: service-foo
kind: ConfigMap
metadata:
  name: service-foo-metadata-mffdh85mct
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: service-foo
  name: service-foo
spec:
  ports:
  - name: 80-4567
    port: 80
    protocol: TCP
    targetPort: 4567
  selector:
    app: service-foo
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: service-foo
  name: service-foo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-foo
  template:
    metadata:
      labels:
        app: service-foo
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: service-foo-metadata-mffdh85mct
        image: ghcr.io/yuya-takeyama/monorepo/service-foo:develop.c5d548f5aec5f362ef1079e98336bca2555739f4
        name: service-foo
