apiVersion: v1
data:
  GITHUB_SHA: e8d317d1ba5b2911bf2ce7c01d2d254bf642b728
  NAMESPACE: develop
  OVERLAY: develop
  SERVICE_NAME: service-foo
kind: ConfigMap
metadata:
  name: service-foo-metadata-6cbk5fd22c
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: service-foo
  name: service-foo
spec:
  ports:
  - name: 80-4567
    port: 80
    protocol: TCP
    targetPort: 4567
  selector:
    app: service-foo
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: service-foo
  name: service-foo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-foo
  template:
    metadata:
      labels:
        app: service-foo
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: service-foo-metadata-6cbk5fd22c
        image: ghcr.io/yuya-takeyama/monorepo/service-foo:develop.e8d317d1ba5b2911bf2ce7c01d2d254bf642b728
        name: service-foo
