apiVersion: v1
data:
  GITHUB_SHA: ec07602ed752ba0fc2856048fc100a46d3503eae
  NAMESPACE: develop
  OVERLAY: develop
  SERVICE_NAME: service-foo
kind: ConfigMap
metadata:
  name: service-foo-metadata-mf9m4975bm
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: service-foo
  name: service-foo
spec:
  ports:
  - name: 80-4567
    port: 80
    protocol: TCP
    targetPort: 4567
  selector:
    app: service-foo
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: service-foo
  name: service-foo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-foo
  template:
    metadata:
      labels:
        app: service-foo
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: service-foo-metadata-mf9m4975bm
        image: ghcr.io/yuya-takeyama/monorepo/service-foo:develop.ec07602ed752ba0fc2856048fc100a46d3503eae
        name: service-foo
