apiVersion: v1
data:
  GITHUB_SHA: e553cd622c306efef5cc369046ab13dc79286d12
  NAMESPACE: develop
  OVERLAY: develop
  SERVICE_NAME: service-foo
kind: ConfigMap
metadata:
  name: service-foo-metadata-t67hm7b8bg
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: service-foo
  name: service-foo
spec:
  ports:
  - name: 80-4567
    port: 80
    protocol: TCP
    targetPort: 4567
  selector:
    app: service-foo
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: service-foo
  name: service-foo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-foo
  template:
    metadata:
      labels:
        app: service-foo
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: service-foo-metadata-t67hm7b8bg
        image: ghcr.io/yuya-takeyama/monorepo/service-foo:develop.e553cd622c306efef5cc369046ab13dc79286d12
        name: service-foo
