apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: frontend
          servicePort: 80
      - path: /static/*
        backend:
          serviceName: frontend
          servicePort: 80
      - path: /foo
        backend:
          serviceName: service-foo
          servicePort: 80
      - path: /bar
        backend:
          serviceName: service-bar
          servicePort: 80
