apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: ingress
spec:
  routes:
    - conditions:
      - prefix: /foo
      services:
        - name: service-foo
          port: 80
    - conditions:
      - prefix: /bar
      services:
        - name: service-bar
          port: 80
    - conditions:
      - prefix: /
      services:
        - name: frontend
          port: 80
  virtualhost:
    fqdn: ${NAMESPACE}.gke.yuyat.jp
