apiVersion: v1
data:
  GITHUB_SHA: 30ee192af0855aac3d78f0c77aabefd32114faf5
  NAMESPACE: develop
  OVERLAY: develop
  SERVICE_NAME: ingress
kind: ConfigMap
metadata:
  name: ingress-metadata-768gm59bgg
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: frontend
          servicePort: 80
        path: /
      - backend:
          serviceName: service-foo
          servicePort: 80
        path: /foo
      - backend:
          serviceName: service-bar
          servicePort: 80
        path: /bar
