apiVersion: v1
data:
  GITHUB_SHA: 00364684957ef6d2ed663a34dab9e46bc2dcb6e2
  NAMESPACE: develop
  OVERLAY: develop
  SERVICE_NAME: ingress
kind: ConfigMap
metadata:
  name: ingress-metadata-87hmkft47g
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: frontend
          servicePort: 80
        path: /
      - backend:
          serviceName: service-foo
          servicePort: 80
        path: /foo
      - backend:
          serviceName: service-bar
          servicePort: 80
        path: /bar
