apiVersion: v1
data:
  GITHUB_SHA: 20aed7e0bd4f2cb6456ccfb0cf2e06ef12a94552
  NAMESPACE: develop
  OVERLAY: develop
  SERVICE_NAME: ingress
kind: ConfigMap
metadata:
  name: ingress-metadata-cdcb7t57t5
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: frontend
          servicePort: 80
        path: /
      - backend:
          serviceName: service-foo
          servicePort: 80
        path: /foo
      - backend:
          serviceName: service-bar
          servicePort: 80
        path: /bar
