apiVersion: v1
data:
  GITHUB_SHA: cba5a1d5d769e4747d73890b78ff8c0aa4d44d6f
  NAMESPACE: develop
  OVERLAY: develop
  SERVICE_NAME: ingress
kind: ConfigMap
metadata:
  name: ingress-metadata-h6k84dcgtt
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: frontend
          servicePort: 80
        path: /
      - backend:
          serviceName: service-foo
          servicePort: 80
        path: /foo
      - backend:
          serviceName: service-bar
          servicePort: 80
        path: /bar
