name: push-to-manifest-repo

inputs:
  github-token:
    description: GitHub API Token to interact with GitHub repo
    required: true
  service-name:
    description: Service name to build
    required: true
  namespace:
    description: Kubernetes namespace to deploy to
    required: true
  manifest-path:
    description: Path to store manifests
    required: true
  branch-prefix:
    description: Prefix of branch name
    required: true
  commit-message:
    description: Commit message
    required: true
  pull-request-title:
    description: Title of Pull Request
    required: true
  pull-request-body:
    description: Body of Pull Request
    required: true

runs:
  using: composite
  steps:
    - run: |
        SERVICE_NAME="${{ inputs.service-name }}" \
          NAMESPACE="${{ inputs.namespace }}" \
          GITHUB_TOKEN="${{ inputs.github-token }}" \
          MANIFEST_PATH="${{ inputs.manifest-path }}" \
          BRANCH_PREFIX="${{ inputs.branch-prefix }}" \
          COMMIT_MESSAGE="${{ inputs.commit-message }}" \
          PULL_REQUEST_TITLE="${{ inputs.pull-request-title }}" \
          PULL_REQUEST_BODY="${{ inputs.pull-request-body }}" \
          ${{ github.action_path }}/action.sh
      shell: bash
