name: push-to-manifest-repo

inputs:
  github-token:
    description: GitHub API Token to interact with GitHub repo
    required: true
  service-name:
    description: Service name to build
    required: true
  namespace:
    description: Kubernetes namespace to deploy to
    required: true
  git-user-email:
    description: Git user email
    required: true
  git-user-name:
    description: Git user name
    required: true
  manifest-path:
    description: Path to store manifests
    required: true

runs:
  using: 'composite'
  steps:
    - run: |
        SERVICE_NAME="${{ inputs.service-name }}" \
          NAMESPACE="${{ inputs.namespace }}" \
          GITHUB_TOKEN="${{ inputs.github-token }}" \
          GIT_USER_EMAIL="${{ inputs.git-user-email }}" \
          GIT_USER_NAME="${{ inputs.git-user-name }}" \
          MANIFEST_PATH="${{ inputs.manifest-path }}" \
          ${{ github.action_path }}/action.sh
      shell: bash
