name: build-manifest
description: Build Kubernetes manifest using kustomize and envsub

inputs:
  service-name:
    description: Service name to build
    required: true
  overlay:
    description: Overlay name to use build with kustomize
    required: true
  namespace:
    description: Kubernetes namespace to deploy to
    required: true
  image-tag:
    description: Docker image tag
    required: false
  github-sha:
    description: $GITHUB_SHA
    required: true
    default: ${{ github.sha }}
  manifest-path:
    description: Path to store manifests
    required: true

runs:
  using: 'node12'
  main: dist/index.js
