name: generate-argocd-app

inputs:
  overlay:
    description: Overlay name to use build with kustomize
    required: true
  namespace:
    description: Kubernetes namespace to deploy to
    required: true
  repo-url:
    description: Repository URL to where Argo CD pull from
  manifest-path:
    description: Path to store manifests
    required: true

runs:
  using: 'composite'
  steps:
    - run: |
        OVERLAY="${{ inputs.overlay }}" \
          NAMESPACE="${{ inputs.namespace }}" \
          REPO_URL="${{ inputs.repo-url }}" \
          MANIFEST_PATH="${{ inputs.manifest-path }}" \
          ${{ github.action_path }}/action.sh
      shell: bash
