name: generate-argocd-app

inputs:
  overlay:
    description: Overlay name to use build with kustomize
    required: true
  namespace:
    description: Kubernetes namespace to deploy to
    required: true

runs:
  using: 'composite'
  steps:
    - run: |
        OVERLAY="${{ inputs.overlay }}" \
          NAMESPACE="${{ inputs.namespace }}" \
          ${{ github.action_path }}/action.sh
      shell: bash
