name: generate-image-tags

inputs:
  image-name-prefix:
    description: Prefix of image name
    required: true
    default: ghcr.io/${{ github.repository }}/
  service-name:
    description: Service name
    required: true
  namespace:
    description: Kubernetes namespace to deploy to
    required: true
  github-sha:
    required: true
    default: ${{ github.sha }}
outputs:
  image-tags:
    description: Line-delimited list of generated image tags
    value: ${{ steps.action.outputs.image-tags }}

runs:
  using: 'composite'
  steps:
    - id: action
      run: |
        image_name="${{ inputs.image-name-prefix }}${{ inputs.service-name }}"
        image_tags="${image_name}:${{ inputs.namespace }}.${{ inputs.github-sha }}"

        echo "::set-output name=image-tags::$image_tags"
      shell: bash
