apiVersion: v1
data:
  GITHUB_SHA: cba5a1d5d769e4747d73890b78ff8c0aa4d44d6f
  NAMESPACE: pr-40
  OVERLAY: staging
  SERVICE_NAME: frontend
kind: ConfigMap
metadata:
  name: frontend-metadata-6hfc6mk22f
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: frontend
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: ghcr.io/yuya-takeyama/monorepo/frontend:pr-40.cba5a1d5d769e4747d73890b78ff8c0aa4d44d6f
        name: frontend
