apiVersion: v1
data:
  GITHUB_SHA: e8d317d1ba5b2911bf2ce7c01d2d254bf642b728
  NAMESPACE: develop
  OVERLAY: develop
  SERVICE_NAME: frontend
kind: ConfigMap
metadata:
  name: frontend-metadata-c2g47db975
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: frontend
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: ghcr.io/yuya-takeyama/monorepo/frontend:develop.e8d317d1ba5b2911bf2ce7c01d2d254bf642b728
        name: frontend
