name: actions / build-manifest

on:
  pull_request:
    branches-ignore:
      - release
      - master
    paths:
      - .github/actions/build-manifest/**
      - .github/workflows/actions--build-manifest.yaml
      - service-foo/ingress/**
      - service-foo/kubernetes/**

  push:
    branches:
      - develop
      - release
      - master
    paths:
      - .github/actions/build-manifest/**
      - .github/workflows/actions--build-manifest.yaml
      - service-foo/ingress/**
      - service-foo/kubernetes/**

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: config
        uses: ./.github/actions/config
      - uses: ./.github/actions/build-manifest
        with:
          service-name: service-foo
          overlay: staging
          namespace: pr-123
          image-tag: ghcr.io/yuya-takeyamma/monorepo/service-foo:pr-123.deadbeef
          github-sha: deadbeef
          manifest-path: ${{ fromJSON(steps.config.outputs.config).manifest-repository.checkout-path }}
      - name: Check the result of service-foo
        run: |
          diff -u \
            .github/actions/build-manifest/test/service-foo-expected-result.yaml \
            ${{ fromJSON(steps.config.outputs.config).manifest-repository.checkout-path }}/staging/pr-123/service-foo/manifest.yaml
      - uses: ./.github/actions/build-manifest
        with:
          service-name: ingress
          overlay: staging
          namespace: pr-123
          github-sha: deadbeef
          manifest-path: ${{ fromJSON(steps.config.outputs.config).manifest-repository.checkout-path }}
      - name: Check the result of ingress
        run: |
          diff -u \
            .github/actions/build-manifest/test/ingress-expected-result.yaml \
            ${{ fromJSON(steps.config.outputs.config).manifest-repository.checkout-path }}/staging/pr-123/ingress/manifest.yaml
