name: delete-staging

on:
  pull_request:
    types: [closed]

jobs:
  delete-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: config
        uses: ./.github/actions/config
      - uses: actions/checkout@v2
        with:
          repository: ${{ fromJSON(steps.config.outputs.config).manifest-repository.checkout }}
          ref: master
          path: ${{ fromJSON(steps.config.outputs.config).manifest-repository.checkout-path }}
          token: ${{ secrets.BUILD_GITHUB_TOKEN }}
      - run: |
          cd "${{ fromJSON(steps.config.outputs.config).manifest-repository.checkout-path }}"
          pr_number="${{ github.event.number }}"
          rm -rf "applications/staging/pr-${pr_number}"
          rm -rf "staging/pr-${pr_number}"
      - uses: ./.github/actions/push-to-manifest-repo
        with:
          github-token: ${{ secrets.BUILD_GITHUB_TOKEN }}
          namespace: ${{ fromJSON(matrix.build-params).namespace }}
          manifest-path: ${{ fromJSON(steps.config.outputs.config).manifest-repository.checkout-path }}
          branch-prefix: delete-staging
          commit-message: Remove staging pr-${{ github.event.number }}
          pull-request-title: Remove staging pr-${{ github.event.number }}
          pull-request-body: https://github.com/${{ github.repository }}/pull/${{ github.event.number }} has been closed.
