name: service-bar / build

on:
  pull_request:

  push:
    branches:
      - develop
      - release
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CONTAINER_REGISTRY_GITHUB_TOKEN }}
      - id: build-params
        uses: ./.github/actions/generate-build-params
        with:
          image-name: service-bar
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: service-bar
          tags: ${{ steps.build-params.outputs.image-tags }}
